services:
#  backend:
#    build:
#      context: .
#      dockerfile: backend/Dockerfile
#    container_name: meteoapi
#    restart: unless-stopped
#    env_file:
#      - .env
#    environment:
#      - PYTHONPATH=/app
#    volumes:
#      - ./backend:/app
#    ports:
#      - "${METEOCATSAPI_PORT}:${METEOCATSAPI_PORT}"
#    command: bash -c "python -m backend.app"
#    networks:
#      - app-network

#  frontend:
#    build:
#      context: ./frontend/forecastapi
#      dockerfile: Dockerfile
#    container_name: vue_frontend
#    restart: unless-stopped
#    ports:
#      - "5173:5173"
#    volumes:
#      - ./frontend/forecastapi:/app
#    depends_on:
#      - backend
#    networks:
#      - app-network
  web:
    build:
      context: frontend/forecastapi/
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./frontend/forecastapi:/project
      - /project/node_modules
networks:
  app-network:
    driver: bridge