services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: meteoapi
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
    ports:
      - "${METEOCATSAPI_PORT}:${METEOCATSAPI_PORT}"
    command: bash -c "python -m backend.app"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vue_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/forecastapi:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge